config/routes.rb
Rails.application.routes.draw do
  root 'home#dashboard'

  post 'user/:id/follow' => 'following#create', as: :follow_user
  post 'user/:id/stop-following' => 'following#delete', as: :stop_following_user

  get 'cheet/:id' => 'cheets#detail', as: :cheet
  get 'newcheets' => 'cheets#new', as: :new
  post 'cheets' => 'cheets#create', as: :cheets

  get 'sign_in' => 'sessions#new', as: :sign_in
  post 'sign_in' => 'sessions#create'
  delete 'sign_in' => 'sessions#delete', as: :sign_out

  get '/users/new' => 'users#new', as: :sign_up
  post '/users' => 'users#create', as: :users

  get 'users/new'
end

app/models/cheet.rb
class Cheet < ActiveRecord::Base
  belongs_to :user
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" interface, and also to followers
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  acts_as_follower
  acts_as_followable
  has_many :cheets  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action do
    @current_user = User.find_by id: session[:user_id]
  end

  def authenticate_user!
    if @current_user.blank?
      redirect_to sign_in_path, notice: 'Please Sign In'
    end
  end

  def sign_in user
    session[:user_id] = user.id
  end

  def sign_out
    session.delete :user_id
  end

  def user_signed_in?
    @current_user.present?
  end
  helper_method :user_signed_in?

end

app/controllers/cheets_controller.rb
class CheetsController < ApplicationController

  before_action :authenticate_user!

  def detail
    @cheet = Cheet.find params[:id]
  end

  def new
    @cheet = Cheet.new
  end

  def create
    @cheet = Cheet.new params.require(:cheet).permit(:entry)
    @cheet.user = @current_user
    if @cheet.save
      redirect_to root_path
    else
      render :new
    end
  end
end

app/controllers/following_controller.rb
class FollowingController < ApplicationController

  before_action :authenticate_user!

  def create
    new_user = User.find params[:id]
    @current_user.follow new_user
    redirect_to root_path, notice: "You have followed #{new_user.email}"
  end

  def delete
    new_user = User.find params[:id]
    @current_user.stop_following new_user
    redirect_to root_path, notice: "You have stopped following #{new_user.email}"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_action :authenticate_user!

  def dashboard
    @users = User.where.not(id: @current_user.id)

    @following_users = @current_user.following_users

    @following_users_ids = @following_users.pluck(:id)

    @cheet_ids = @following_users_ids << @current_user.id

    @cheets = Cheet.where(id: @cheet_ids)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:email]
    password = params[:password]

    user = User.find_by email: email

    if user && user.authenticate(password)
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash.now[:alert] = 'Something is wrong with your email or password.'
      render :new
    end
  end

  def delete
    session.delete :user_id
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new params.require(:user).permit(:email, :password, :password_confirmation)
    if @user.save
      #sign in
      session[:user_id] = @user.id
      #redirect
      redirect_to root_path
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cheets_helper.rb
module CheetsHelper
end

app/helpers/following_helper.rb
module FollowingHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cheets/detail.html.erb
<h1>Cheets#detail</h1>
<p>Find me in app/views/cheets/detail.html.erb</p>

app/views/cheets/new.html.erb
<h4> Add to the Chatter </h4>

<%= form_for @cheet do |f| %>

  <div class="cheet_entry">
    <%= f.text_field :entry %>
  </div>

  <div>
    <%= f.submit %>
  </div>

<% end %>

app/views/following/create.html.erb
<h1>Following#create</h1>
<p>Find me in app/views/following/create.html.erb</p>

app/views/following/delete.html.erb
<h1>Following#delete</h1>
<p>Find me in app/views/following/delete.html.erb</p>

app/views/home/dashboard.html.erb
<div class="my_content_container">
  <div class="all_cheets">
    <% @cheets.each do |cheet| %>
      <div class="individual_cheet">
          <p class="individual_entry"> <%= cheet.entry %></p>
          <p class="cheet_username"><%= cheet.user.email %></p>
      </div>
    <% end %>
  </div>

  <div class="all_users_box">
    <h4> Users </h4>
    <% @users.each do |user| %>
      <p>
        <% if @current_user.following? user %>
          <%= link_to "Stop Following #{user.email}", stop_following_user_path(id: user.id), method: :post %>
        <% else %>
          <%= link_to "Follow #{user.email}", follow_user_path(id: user.id), method: :post %>
        <% end %>
      </p>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chatter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
</head>
<body>
  <div class="my_nav">
    <div class="top_container">
      <% if @current_user %>
        <div class="username_greeting">
          <i class="fa fa-home"><%= link_to "#{@current_user.email}", root_path %></i>
        </div>
        <div>
          <i class="fa fa-sign-out"><%= link_to 'Sign Out', sign_out_path, method: :delete %></i>
        </div>
        <%= link_to new_path do %>
          <i class="fa fa-pencil"> Add to the Chatter</i>
        <% end %>
      <% else %>
        Welcome
      <% end %>
    </div>
    <div class="my_warnings">
      <% if alert %>
        <div class="alert alert-danger"> <%= alert %> </div>
      <% end %>
      <% if notice %>
        <div class="alert alert-info"> <%= notice %> </div>
      <% end %>
    </div>
  </div>
  <div class="my_logo">
    <h1>Chatter</h1>
    <h3>Because the internet doesn't have enough chatter already</h3>
  </div>
  <div class="my_content">
    <%= yield %>
  </div>
</body>
</html>

app/views/users/new.html.erb
<h4>Please sign up and add to the chatter.</h4>

<div class="sign_up">
  <%= simple_form_for @user do |f| %>
    <%= f.input :email %>
    <%= f.input :password %>
    <%= f.input :password_confirmation, label: 'Password Confirmation' %>
    <%= f.submit 'Sign Up'  %>

  <% end %>
</div>